### ISSUE TITLE
Question: How to handle different slices, if they are not completely the same structure

### ISSUE THREAD

**Issue by christiangentges** [UMEssen/FHIR-PYrate#117]
Hello from Aachen,

here in Aachen we are using FHIR-PYrate and like it a lot.

We've got a question how to handle some specific case for data with slices of elements.
In case we have slices in our resources, I see cases, where we are losing the association to the element after using query_to_dataframe.
Let me give you an example to show, what I mean:

This is our python code:

```Python
df_patients = search.query_to_dataframe(  # Wrapper function
    bundles_function=search.steal_bundles,  # Non-parallel function that iterates through the bundles and returns them
    resource_type="Patient",
    request_params={
        "_lastUpdated": "ge2022-12",
    },
    fhir_paths=["id", "meta.source", "meta.profile", "meta.lastUpdated", "identifier.assigner.reference", \
    "gender", "birthdate", "name.given", "name.prefix",	"name.family", "name.suffix", "name.text", "name.use", "address.line", \
    "address.zip", "address.city", "address.country", "address.type", "telecom.system", "telecom.use", "telecom.value", \
    "multipleBirthBoolean", "identifier.type.coding.system", "identifier.type.coding.code", "identifier.type.text",	"identifier.value"]
)
```

The most interesting part is, what happens with the names, because there are resources on our FHIR-Server with two slices of names elements. One of these has attribut "use" and one does not have attribut "use":

```JSON
{
    "resourceType": "Patient",
    "id": "123456789",
...
...
...
    "name": [
        {
            "text": "MAX MUSTERMANN",
            "family": "MUSTERMANN",
            "given": [
                "MAX"
            ]
        },
        {
            "use": "official",
            "text": "Max Mustermann",
            "family": "Mustermann",
            "given": [
                "Max"
            ]
        }
    ],
...
...
...
}
```

This leads to the following entries in the pandas dataframe:
```
      name.family                                                     [MUSTERMANN, Mustermann]
      name.given                                                    [MAX, Max]
      name.prefix                                                                   None
      name.suffix                                                                   None
      name.text                                                     [MAX MUSTERMANN, Max Mustermann]
      name.use                                                                  official
```

My issue with this is the, I cannot determine, which of the two names is the official name and which is not, because the attribute is only a string. If it would be a list like [None, official] or [official, None], I could see, if the attribut official belongs to the first or second name.

Is there a way to use FHIR-PYrate, still maintaining the relation of the attributes to each other in such cases, e.g. by numbering the slices?

**Comment by giuliabaldini** [comment]
Hey there,

thank you for explaining your issue so much in detail, that's great!

So I see two options for this:

1. You can number your attributes, if you are sure of the order they will appear in:
```
df_patients1 = search.query_to_dataframe( 
        bundles_function=search.steal_bundles,
        resource_type="Patient",
        request_params={
            "_lastUpdated": "ge2022-12",
        },
        fhir_paths=[
            "id",
            ("all", "name"),
            ("family_first", "name[0].family"),
            ("given_first", "name[0].family"),
            ("family_second", "name[1].family"),
            ("given_second", "name[1].family"),
        ],
    )
```
In this case, you will always know which is where.

2. You can check for existence using FHIRPath expresssions:
```
df_patients2 = search.query_to_dataframe( 
        bundles_function=search.steal_bundles,
        resource_type="Patient",
        request_params={
            "_lastUpdated": "ge2022-12",
        },
        fhir_paths=[
            "id",
            ("given_name_no_use", "name.where(use.exists().not()).given"),
            ("family_name_no_use", "name.where(use.exists().not()).family"),
            ("given_name_official", "name.where(use='official').given"),
            ("family_name_official", "name.where(use='official').family"),
        ],
    )
```

In this case, you first get the ones that have no `use` attribute, and then the ones with `official`. 

I hope I answered your question correctly, please tell me if you have any other questions!

**Comment by christiangentges** [comment]
Thank you for your fast and detailed response to my question. Your second option will work in out case.
Both options have given me a lot more insight to what is possible to do with FHIR-PYrate.

**Comment by giuliabaldini** [comment]
Ah I also just noticed a little mistake, in the first option I wanted to write:
```
("family_first", "name[0].family"),
("given_first", "name[0].given"),
("family_second", "name[1].family"),
("given_second", "name[1].given"),
```
But I think you understood the message anyway!

If you need any help, we are available any time!

Best,
Giulia
